chore(ci): add prettier lint
werf/common-ci pull request #3
Opened 2024-12-25 14:04 UTC by Fral738

2024-12-28 14:18 UTC, ilya-lesikov requested changes

2024-12-28 14:18 UTC, ilya-lesikov commented on .github/workflows/lint.yml
> +        directory: ${{ fromJson(inputs.directories) }}
Looks really ugly when this workflow is used:
```
  directories: '["."]'
```
Maybe just comma-separated, if possible?
```
  directories: dir1
  directories: dir/dir/dir, dir2/dir2/dir2
```

2024-12-28 14:18 UTC, ilya-lesikov commented on .github/workflows/lint.yml
> +        run: ${{ inputs.cmd }}
This cmd thing is meh, can we just have Taskfiles everywhere with the same task name (`lint:golangci-lint` ?) and use it by default? If this cmd thing is temporary, then alright.

2024-12-28 14:18 UTC, ilya-lesikov commented on .github/workflows/lint.yml
> +        run: ${{ inputs.cmd }}
And if we have Taskfiles everywhere, then let's make it clear that "inputs.directory" is about where to find Taskfile.yaml, not just working dir. Maybe even better to just pass the Taskfile path via `-t` flag to the `task` executable instead.

2024-12-28 14:18 UTC, ilya-lesikov commented on .github/workflows/lint.yml
> +        required: true
Maybe not required, but "." by default?

2025-01-14 11:25 UTC, alexey-igrychev commented on .github/workflows/lint.yml
> +      forceSkip:
naming convention

2025-01-14 11:25 UTC, alexey-igrychev commented on .github/workflows/lint.yml
> +      go-version-file-dir:
**go-version**-file-dir ?

2025-01-15 13:34 UTC, merged